### PR TITLE
Add requirements for low latency streaming use cases

### PR DESCRIPTION
**Pull request by aboba**
This is an attempt to add requirements for low latency streaming use cases.
The requirements for game streaming and other low latency streaming uses cases are somewhat different, so they each have their own section.

Partial fix for https://github.com/w3c/webrtc-nv-use-cases/issues/62

***
<a href="https://pr-preview.s3.amazonaws.com/aboba/webrtc-nv-use-cases/pull/75.html" title="Last updated on Sep 7, 2022, 8:14 PM UTC (2de0efa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-nv-use-cases/75/c96cf4c...aboba:2de0efa.html" title="Last updated on Sep 7, 2022, 8:14 PM UTC (2de0efa)">Diff</a>

### CODE REVIEW

**Comment by aboba** [comment]
@fippo PTAL.

**Comment by drkron** [comment]
Thanks @aboba!
I think that this is a great initiative.

What do you think of adding another requirement regarding reduced jitter buffer on the receiving client?

**Review by fippo — APPROVED** [review]
LGTM, I like the distinction between game streaming (ultra low latency streaming with less than 100ms latency, [this](https://youtu.be/XXvKlpkJjFU?t=150) shows some numbers) and low latency streaming (sub-second)

In terms of requirements for gaming I can think of two:
* control how data is sent out over the datachannel, since you want keyboard or mouse movements to be prioritized over statistics. This actually provides a [solution](https://w3c.github.io/webrtc-priority/#new-rtcdatachannel-attribute)
* control over jitter buffer and rendering delay. @drkron may be able to help out with that one

**Comment by drkron** [comment]
The control of jitter buffer and rendering delay could be generalized to a Quality-of-Service API, where latency is traded for the perceived smoothness (dropped frames, freezes, etc).

**Comment by aboba** [comment]
@fippo @drkron Added the jitter buffer/rendering control requirements.

**Comment by aboba** [comment]
Comments from TPAC 2022:  
     1. For both use cases: RTCDataChannel in Workers.
     2. For game streaming: Streaming input from GamePad via a worker.
     3. For game streaming: Streaming input from AR/VR headsets (via RTP?).

**Pull request merged**
