### PR TITLE
Requirements Secure Web Conferencing 

### PR DESCRIPTION
**Pull request by fluffy**

### CODE REVIEW

**Comment by alvestrand** [comment]
Definitely spellcheck needed :-)
good point about the "untrusted JS" case needing to have isolation between media and the JS in addition to having isolation between media and the media relay.
Wonder if there's a third level here, where the JS is trusted with access to the media (so it can paint funny hats) but exit channels are monitored so that leaking the media won't happen - in that case leaking the keys to the conferencing server would allow undetectable wiretapping. Is the difference between locally detectable and undetectable wiretapping large enough to bother about?

**Comment by fluffy** [comment]
I think this is ready for some review and discussion

**Comment by murillo128** [comment]
can we define what "the Javavcript" means in the following phrase? 

>The end to end keys are not revealed to the JavaScript.

**Comment by murillo128** [comment]
@alvestrand :

 > Wonder if there's a third level here, where the JS is trusted with access to the media (so it can paint funny hats) but exit channels are monitored so that leaking the media won't happen

You mean like a kind of sandboxed webworker or whatwg TransforStream which can only in/out media from one stream to another (no postMesssage or fetch/xhr available)?

**Comment by fluffy** [comment]
> can we define what "the Javascript" means in the following phrase?
> 
> > The end to end keys are not revealed to the JavaScript.

I can but try and make that clearer but I think it is relatively clear as the JavaScript running in the browser. 

I could update the 2nd case to talk about Javascript being loaded from two different locations, one of which was trusted to see the media and keys but ran in a sandbox restricted to key management, and one of which was not but that dealt with UI of applications and other data. But that seems more like a solution than a requirement.

**Comment by murillo128** [comment]
> I can but try and make that clearer but I think it is relatively clear as the JavaScript running in the browser

There are different javascripts running on the browser, like the IdP script which is trusted and runs in secure context. If you refer to the "untrusted javascript app" then I would be ok with it, if you refer to "any kind of javascript running on the browser" I would oppose.

Also, I would like to change the "end to end keys" by "end to end keying material".

**Comment by murillo128** [comment]
I have read the full paragraph again:

> A possible solution this problem is the browser to negotiate end to
  end encryption keys using approach such as the IETF PERC work. The end
  to end keys are not revealed to the JavaScript.

Is the "end to end keys not revealed to the javascript" a part of the description of PERC or a description of the use case. I mean, would this mean the same?

> A possible solution this problem is the browser to negotiate end to
  end encryption keys using approach such as the IETF PERC work in which the end
  to end keys are not revealed to the JavaScript.

**Comment by fluffy** [comment]
The use case is that all the server that provide the Javascript code for the WebRTC stuff as well as the media servers are *not* trusted to see the media.

**Comment by fluffy** [comment]
I should add, that is only for one of the use cases, there are two use cases here and one of them is written to align with what I suspect you want to do where at least some of the JavaScript is trusted to see keys for media or the media.

**Comment by youennf** [comment]
End-to-end encryption is currently being used for secure message delivery, including text.
The current description of this use case seems to ignore requirements for text/data channel cases (say I am sharing files or images with all video conference participants).
Is there a specific reason?

It also strikes me that while isolated streams allow some level of protection for camera and microphone content (for both sender web application and receiver if it is a web application), I do not know an easy way to implement the same level of protection for text messages in web browsers.
Is there a plan to work on fixing this as well?

**Comment by lgrahl** [comment]
Agree with @youennf that the forwarding should apply to all kinds of data.

But I can't imagine a similar mechanism for the *untrusted JS* use case. It would have to be some kind of `IsolatedBlob` that can be attached to only very specific sinks, such as a *download sink*.

**Pull request merged**
